<a href="https://colab.research.google.com/github/mankook/acornacademy/blob/master/01_vector_matrix_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow 학습 

# colab을 사용하는 이윺
- GPU를 사용가능 
- 컴퓨터 한대를 무료 사용
- 기반 시스템 : ubuntu 
- 저장공간은 google drive에 저장 


In [4]:
%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)  
from tensorflow import keras
print(keras.__version__)

1.15.2
2.2.4-tf


In [ ]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 13932407433494015126
 xla_global_id: -1, name: "/device:GPU:0"
 device_type: "GPU"
 memory_limit: 16154099712
 locality {
   bus_id: 1
   links {
   }
 }
 incarnation: 2667352307228307424
 physical_device_desc: "device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0"
 xla_global_id: 416903419]

In [ ]:
# 현재 디렉터리의 내용을 확인 : 멀티 유저 마다 디렉터리를 제공 (home) 
#!ls   # window command : dir 
#!ls /bin  # 리눅스의 최상위 폴더   / 로 시작 
!cd /
!ls

sample_data


In [ ]:
!ls /bin

bash	       hostname       su
bunzip2        journalctl     sync
bzcat	       kill	      systemctl
bzcmp	       kmod	      systemd
bzdiff	       less	      systemd-ask-password
bzegrep        lessecho       systemd-escape
bzexe	       lessfile       systemd-hwdb
bzfgrep        lesskey	      systemd-inhibit
bzgrep	       lesspipe       systemd-machine-id-setup
bzip2	       ln	      systemd-notify
bzip2recover   login	      systemd-sysusers
bzless	       loginctl       systemd-tmpfiles
bzmore	       ls	      systemd-tty-ask-password-agent
cat	       lsblk	      tar
chgrp	       lsmod	      tempfile
chmod	       mkdir	      touch
chown	       mknod	      true
cp	       mktemp	      udevadm
dash	       more	      ulockmgr_server
date	       mount	      umount
dd	       mountpoint     uname
df	       mv	      uncompress
dir	       networkctl     vdir
dmesg	       nisdomainname  wdctl
dnsdomainname  pidof	      which
domainname     ps	      ypdomainname
echo	       pwd	      zcat
egrep	     

In [ ]:
!mkdir 'data'

In [ ]:
!ls

data  sample_data


In [ ]:
cd ..  # cd는 !없이 사용할 것 

/


In [ ]:
cd /content/data

/content/data


In [ ]:
!ls

bin	 datalab  home	 lib64	opt	    root  srv		     tmp    var
boot	 dev	  lib	 media	proc	    run   sys		     tools
content  etc	  lib32  mnt	python-apt  sbin  tensorflow-1.15.2  usr


In [ ]:
cd     /content/drive/MyDrive/dataset

/content/drive/MyDrive/dataset


In [ ]:
!ls

pima.csv


In [ ]:
import pandas as pd
# False , 0 
df=pd.read_csv("pima.csv", index_col = 0)
df.head()

npreg  glu  bp  skin   bmi    ped  age type
1      6  148  72    35  33.6  0.627   50  Yes
2      1   85  66    29  26.6  0.351   31   No
3      1   89  66    23  28.1  0.167   21   No
4      3   78  50    32  31.0  0.248   26  Yes
5      2  197  70    45  30.5  0.158   53  Yes

In [58]:
import numpy as np
import numpy.linalg
A = np.array([[1,-1,2],[3,2,0]]) # 2행 3열
print(A)
v = np.array([1,2,3]) 
print("행벡터", v)
v = np.array( [[2],[1],[3]])
print("3행1열벡터",v)
print("전치")
v = np.transpose(np.array([[2,1,3]])) # 면과 행이 변경
print(v)

w = np.dot(A,v) # 2x3  3x1 => 2x1
print("내적의 결과 ")
print(w)

[[ 1 -1  2]
 [ 3  2  0]]
행벡터 [1 2 3]
3행1열벡터 [[2]
 [1]
 [3]]
전치
[[2]
 [1]
 [3]]
내적의 결과 
[[7]
 [8]]


In [59]:
# 내적은 두 벡터의 순서가 없다. ( 크기를 고려한 사이각 )
v = np.array([9,  10])
w = np.array([11, 12])

print("벡터내적", v.dot(w))
print("벡터내적", np.dot(v, w))
print("벡터내적", np.dot(w, v))

벡터내적 219
벡터내적 219
벡터내적 219


In [61]:
from numpy import linalg as LA
x = np.array([1.0,1.0])
print("2차원",LA.norm(x))  
x = np.array([1.0,1.0,1.0]) 
print("3차원",LA.norm(x))
x = np.array([1.0,1.0,1.0,1.0]) 
print("4차원",LA.norm(x))
a = np.arange(9) - 4
print(a)

b = a.reshape((3, 3)) 
print(b)
# norm에 넣으면 벡터로 취급한다. ( 데이터는 메모리에 직선으로 저장 )
print(LA.norm(a))
LA.norm(b)

2차원 1.4142135623730951
3차원 1.7320508075688772
4차원 2.0
[-4 -3 -2 -1  0  1  2  3  4]
[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
7.745966692414834


7.745966692414834

In [62]:
# 문제 : 두벡터의 사이각이 얼마인지 구하시요 
# A 내적 B = |A| |B| cos theta 
a = np.array([0,1,0])
b = np.array([1,0,0])

res = np.dot(a,b)
rad = res / (np.linalg.norm(a) * np.linalg.norm(b))
theta = np.arccos(rad)
print("두벡터의 사이각은 = ", np.degrees(theta))

두벡터의 사이각은 =  90.0


In [63]:
# dot과 matmul의 차이 ( 앞의 행렬의 열수와 뒤의 행렬의 행수가 일치 )
A = np.arange(2*3*4).reshape((2,3,4))
B = np.arange(2*3*4).reshape((2,4,3))
print("내적 : ", np.dot(A,B).shape) # 내적 
print("행렬곱 : ", np.matmul(A,B).shape) # 행렬곱 ( 내부적으로 내적의 연속 )

내적 :  (2, 3, 2, 3)
행렬곱 :  (2, 3, 3)


In [64]:
# broadcasting
B = np.arange(3*4).reshape((4,3))
print("행렬곱 : ", np.matmul(A,B).shape) # 행렬곱 ( 내부적으로 내적의 연속 )

행렬곱 :  (2, 3, 3)


In [ ]:
# 행렬곱의 의미 

In [66]:
# 고유값 분해 ( 고유치, 고유벡터 )
line = np.array([2,4,6])
#축표현( 방향으로 표시 )
xa = np.array([1,0,0])
ya = np.array([0,1,0])
za = np.array([0,0,1])
print("x축으로 투영 ", line.dot(xa))
print("y축으로 투영 ", line.dot(ya))
print("z축으로 투영 ", line.dot(za))

x축으로 투영  2
y축으로 투영  4
z축으로 투영  6


In [67]:
print(line.dot(xa) *xa )
print(line.dot(ya) *ya )
print(line.dot(za) *za )

[2 0 0]
[0 4 0]
[0 0 6]


In [ ]:
# 신경망 방정식의 해 
- 계수가 결정 
- 데이터가 입력 
- 종속변수 (Y) 

In [ ]:
  #  2x + x2  -2 x3 = -3
  #  3x +     1  x3 =  5
  #   x1 +  x2 - x3 = -2 일 때 
  # x1, x2, x3의 해를 구하는 방정식의 해를 구하고 있음 

In [68]:
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b = np.transpose(np.array([[-3,5,-2]])) 
print(b) 


[[-3]
 [ 5]
 [-2]]


In [70]:
x = np.linalg.solve(A,b)
x

array([[ 1.],
       [-1.],
       [ 2.]])

In [71]:
2 * 1 + (-1) + (-2 * 2)

-3

In [72]:
# A계수행렬 * x변수 = b
# 변수 = b/ A계수행렬 
# A계수행렬의 역행렬 * b = 변수의 값 
np.dot(np.linalg.inv(A),b)

array([[ 1.],
       [-1.],
       [ 2.]])

In [73]:
np.linalg.inv(A) @ b

array([[ 1.],
       [-1.],
       [ 2.]])

In [ ]:
# 텐서플로우 
- node + edge로 구성 => graph 
- GPU를 기본구조로 해서 텐서플로우를 설계 ( 게임 - GPU )
- 과학계산용으로 사용 ( 행렬연산 )
- nvidia : CUDA 
- 구조 
  - Constant 상수 
  - Variables 변수 : 가중치를 저장하는 변수 - 반드시 초기화되어야 함 ( 행렬곱 : )
  - placeholder : 외부주입변수 , 실행시에 feeding 
     - GPU 프로그램을 저장 ( 처리될 데이터가 실행시점에서 CPU에서 전달함 )
     - GPU 메모리 공간 ( 2M )
  - 자동으로 데이터 송수신 

In [6]:
def showvalue(t):
    sess = tf.InteractiveSession()
    tf.global_variables_initializer().run()
    print(t.eval())
    sess.close()     

c2, c3 = tf.constant([1.2, 5.6]), tf.constant([-4, -1, 7])
v2, v3 = tf.Variable([2.3, 4.5]), tf.Variable([-2,  3, 5])

In [7]:
showvalue(tf.add_n([c2, v2])) 
showvalue(tf.add_n([c3, v3, v3]))
showvalue(tf.abs(c2))
showvalue(tf.negative(c2))

[ 3.5 10.1]
[-8  5 17]
[1.2 5.6]
[-1.2 -5.6]
